### ISSUE TITLE
Greater than 0 precision do not sum up to 100?

### ISSUE THREAD

**Issue by btantlinger** [kschu91/largest-remainder-method#1]
On the readme you give the example:
```

[
    18.562874251497007,
    20.958083832335326,
    18.562874251497007,
    19.161676646706585,
    22.75449101796407
]
```

Which, with a precision of 2, results in

```
Array
(
    [0] => 18.55
    [1] => 20.94
    [2] => 18.55
    [3] => 19.15
    [4] => 22.74
)

```

But this sums up to 99.93.  Shouldn't it be 100?  Seems like precision with anything other than 0 does not work.

**Comment by kschu91** [comment]
Good catch. I am going to have a look into this soon.
