### ISSUE TITLE
Simple failing test case with precision 2 and 2 values

### ISSUE THREAD

**Issue by amadeann** [kschu91/largest-remainder-method#2]
```
$lr = new Aeq\LargestRemainder\Math\LargestRemainder([0.015, 0.015]);
$lr->setPrecision(2);
print_r($lr->round());
```

Expected result: `[0.02. 0.01]`
Actual result: `[0.0, 0.0]`

**Comment by kschu91** [comment]
Thanks @amadeann for pointing this out. I fixed the algorithm and published a new release: [v1.1](https://github.com/kschu91/largest-remainder-method/releases/tag/v1.1)
